name: Build and Deploy Docs
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8

    # 安装依赖和打包
    - name: Install and Build
      run: pnpm install && pnpm run docs:build

    # 部署到 GitHub Pages
    - name: Deploy vitepress docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        # 要部署的文件夹
        FOLDER: docs/.vitepress/dist
        # 部署的分支，默认 gh-pages
        BRANCH: gh-pages